---
Standards:
  -
    Title: "Career and Professional Development"
    Description: All relevant resources for career development workshops taught by our Career Services Managers
    UID: b43340e1-9052-4b5d-8c8a-24e34ab8210a
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 5d7e93f3-b6cd-4edd-8912-ca9140fae368
        Path: /career-development/career-development.md
      -
        Type: Lesson
        UID: dbb6d2de-c7c5-460d-a7e8-2c2f3fbd7277
        Path: /career-development/professional-development.md
