---
Standards:

  -
    Title: Schedule
    Description: Topics and speakers
    UID: 8c0c928b-2cd6-4f97-90dc-8f7d407af8d1   
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 1b84f226-a69b-4603-977b-d43446996073 
        Path: /overview/overview.md 
  -
    Title: Internship Expectations
    Description: Internship Expecatations with Alice and Jackie
    UID: b22eac8b-d86e-4bf2-b34a-ca6e798c57e7  
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 2cb5fb41-6b23-4a72-bb5c-f1dc8837654b  
        Path: /internshipexpectations/overview.md 
  -
    Title: Remote Internship Tips
    Description: Advice from Previous Cohorts
    UID: 6c516d17-5db5-45f4-a612-2a497f367235 
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 2e19cf22-2a99-4698-bbbf-32b1631c1429 
        Path: /remoteinternship/overview.md          
  - 
    Title: Panel with C13 Interns
    Description: Internship advice from previous interns
    UID: deaa25fa-78a9-4f5c-8a83-5dfacf74d7b3  
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: cdc04da7-a055-479d-83b1-66a662e00eed 
        Path: /internshippanel/overview.md
  -
  
    Title: Managing Up
    Description: How to get the most out of your relationship with your manager
    UID: 02719c5a-553a-4d5b-a31f-8ffe6a817033 
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 6125defb-5458-4797-9e9c-6591f3faf278 
        Path: /managingup/overview.md       
  -
  
    Title: Self Care and Boundary Setting
    Description: Taking care of yourself during internship
    UID: 0ff60020-b1a3-40bd-92b8-c0bb5a848bca  
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 5facedda-958f-4b30-818b-5388085ab137  
        Path: /self-care/overview.md               
  -
    Title: Preparing for Midpoint Reviews
    Description: Keys to a successful midpoint review
    UID: af75fc76-5110-44f0-87a1-3d75acae2cd3 
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 70e3fc68-2def-4c4a-9f08-c3f26c8a2a4c 
        Path: /prepping-for-midpoint-reviews/overview.md
  -
    Title: Managing Impostor Syndrome
    Description: Recognizing and managing impostor syndrome 
    UID: c373707c-e8fb-4052-afa2-eafdd1ce89b9  
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 6b054c2c-fc9d-4b10-96cc-693768bc1b26  
        Path: /impostorsyndrome/overview.md
        
  -
    Title: Interviewer Panel
    Description: SDE Interview Tips from Industry 
    UID: 569c2b07-63f8-4782-b8b9-f934cd471f3b  
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: f40ce4ef-67a3-4294-9e5b-1a59f7c60142  
        Path: /interviewerpanel/overview.md
        
  -
    Title: Technical Resume Workshop
    Description: Review of resume template and resume Q & A 
    UID: ec661c0d-6e6d-454f-ab11-ce7353543c9e 
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 2389a313-844d-4711-afb1-bf514722b1ea 
        Path: /resumeworkshop/overview.md
        
  -
    Title: Behavioral Interviews
    Description: Prep for behavioral interviews and the STAR method 
    UID: 3381f9d8-f339-4a2b-a960-e5d9ad906098 
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 095d02e7-b30f-480f-ad6f-901d704d016a 
        Path: /behavioralinterviews/overview.md
        
  -
    Title: Leveraging LinkedIn
    Description: Mock interview debrief and LinkedIn for job search 
    UID: fe599a78-39c4-419a-95ca-af10ad0e8e0f 
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: e18e4a3b-b198-49e1-8369-be39364ef7f0 
        Path: /leveraginglinkedin/overview.md
        
  -
    Title: Strong habits of an SDE Job Seeker
    Description: Technical job search strategies 
    UID: b249fd6c-6598-4279-a886-f25e8f89b9cf 
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 2c395f57-abc4-46a8-a2fa-956d16f2f2c7
        Path: /SDEjobsearch/overview.md
        
  -
    Title: Professional Networking
    Description: Networking strategies for your career 
    UID: d053247c-5b2f-4e3d-8279-4385e7a2faf0 
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: af2e33f9-a8ee-4c15-94b7-a315ff8d0f84
        Path: /networking/overview.md
        
  -
    Title: Salary Negotiation
    Description: Salary negotiation strategies with Professor Umphress
    UID: 26239b28-888b-49e6-a8cf-98b742345609 
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 91a24944-1872-4162-9d19-8a490be2428d
        Path: /salarynegotiation/overview.md
        
  -
    Title: Breaking down the job offer
    Description: Things to consider when reviewing a job offer
    UID: 61110cb3-4414-4e04-89cf-bd9265f9802c 
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 75763552-64d6-4746-acd3-d1ad9177f1bb
        Path: /joboffers/overview.md
