---
Standards:
  -
    Title: Career & Professional Development
    Description: All relevant resources for career & professional development workshops taught by our Career Services Managers
    UID: b43340e1-9052-4b5d-8c8a-24e34ab8210a
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 5d7e93f3-b6cd-4edd-8912-ca9140fae368
        Path: /career-development/career-development.md
