---
Standards:
  -
    Title: Internship Expectations
    Description: Internship Expecatations with Alice and Jackie
    UID: c206a7d1-8906-4585-a73f-d3bf6dde13da 
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 1f06f3a5-dd8e-4535-939a-b217c7a752d0 
        Path: /internshipexpectations/overview.md 
  -
    Title: Remote Internship Tips
    Description: Advice from Previous Cohorts
    UID: fb7ca18e-462d-49a9-a38f-d3eaf2cfe958  
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 98d6a0e1-7de9-487b-a953-97d1522c5061  
        Path: /remote-internship/overview.md          
  - 
    Title: Panel with C13 Interns
    Description: Internship advice from previous interns
    UID: 92d77dbc-0459-4de8-be6c-f448a121cc3f 
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 04ef43e2-8d68-4689-9b43-569ff5d5b357
        Path: /internshippanel/overview.md
  -
  
    Title: Managing Up
    Description: How to get the most out of your relationship with your manager
    UID: 974825d6-b35c-467f-9d38-7df7f4eb03ed
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: c9f8125a-1ef8-49a2-b08d-3a82da514ade
        Path: /managingup/overview.md            
  -
  
    Title: Self Care and Boundary Setting
    Description: Taking care of yourself during internship
    UID: 4661fd35-2ee4-4061-8b89-35b5385bd59c 
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: efe4dd39-c552-4156-99c0-8943539bc46d 
        Path: /selfcare/overview.md               
 
  -
    Title: Preparing for Midpoint Reviews
    Description: Keys to a successful midpoint review
    UID: 73f47a05-d695-480e-8337-98cf0277fa9c
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: a861d76a-0236-46ca-94a9-70093f15a522
        Path: /prepping-for-midpoint-reviews/preparing-for-midpoint-reviews.md
  -
    Title: Managing Impostor Syndrome
    Description: Recognizing and managing impostor syndrome 
    UID: 4c56f3f6-1e51-4d41-a2ba-214e7f6612af 
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: af1ac27e-d6b6-4622-93fc-d91f142c578f 
        Path: /impostorsyndrome/overview.md
  
