---
Standards:
  -
    Title: Internship Expectations
    Description: Internship Expecatations with Alice and Jackie
    UID: dccfe33a-1d83-4c37-bd61-d60f0cf6d323  
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: cae486a0-91af-44a0-842a-fe7c6443fd41 
        Path: /internshipexpectations/overview.md 
  
